import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#9e3d00',
        'primary-container': '#c64f00',
        'primary-fixed': '#ffdbcd',
        'primary-fixed-dim': '#ffb595',
        'on-primary': '#ffffff',
        'on-primary-container': '#fffbff',
        'on-primary-fixed': '#351000',
        'on-primary-fixed-variant': '#7c2e00',
        'inverse-primary': '#ffb595',
        secondary: '#4e6073',
        'secondary-container': '#cfe2f9',
        'secondary-fixed': '#d1e4fb',
        'secondary-fixed-dim': '#b5c8df',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#526478',
        'on-secondary-fixed': '#091d2e',
        'on-secondary-fixed-variant': '#36485b',
        tertiary: '#71582c',
        'tertiary-container': '#8c7042',
        'tertiary-fixed': '#ffdeaa',
        'tertiary-fixed-dim': '#e3c28c',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fffbff',
        'on-tertiary-fixed': '#271900',
        'on-tertiary-fixed-variant': '#5a4319',
        background: '#f8f9f9',
        surface: '#f8f9f9',
        'surface-bright': '#f8f9f9',
        'surface-dim': '#d9dada',
        'surface-variant': '#e1e3e3',
        'surface-container': '#edeeee',
        'surface-container-high': '#e7e8e8',
        'surface-container-highest': '#e1e3e3',
        'surface-container-low': '#f3f4f4',
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#a23f00',
        'on-background': '#191c1c',
        'on-surface': '#191c1c',
        'on-surface-variant': '#594238',
        'inverse-surface': '#2e3131',
        'inverse-on-surface': '#f0f1f1',
        outline: '#8c7166',
        'outline-variant': '#e0c0b2',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '700' }],
        'kitchen-timer': ['40px', { lineHeight: '40px', letterSpacing: '0.02em', fontWeight: '800' }],
      },
      spacing: {
        'margin-desktop': '32px',
        'margin-mobile': '16px',
        gutter: '20px',
        xl: '64px',
        lg: '40px',
        md: '24px',
        sm: '16px',
        xs: '8px',
        base: '4px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
export default config
